### ISSUE TITLE
Saving the label throws an exception

### ISSUE THREAD

**Issue by dalder** [snowflakech/snowbabel#6]
Since snowbabel only features saving xliff files it fails while saving a label in l10n if the original file in the extension was an xml.

**Comment by hojaonline** [comment]
Hi Daniel,
I found that only xliff file structure could updated in current version. If the extension original language file is xml. Then scheduler found this as xml and manage this as usual xlf file and in BE throws the error.

I code what I found is 
/\* Check for xml body structure */
$bodyOfFileTag = $simpleXmlObject->file->body

in case of xml files with original language is an xml which throws an exception as above. Because in case of xml files it fails since the xml struture is 
eg:  -----------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3locallangExt>
    <data type="array">
        <languageKey index="pt" type="NULL"></languageKey>
    </data>

## </T3locallangExt>

But incase of xliff files it will save with out any issues
eg.---------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<xliff version="1.0">
    <file source-language="en" target-language="pt" datatype="plaintext" original="messages" date="2014-12-02T05:00:05Z" product-name="felogin">
        <header/>
        <body>
                </body>

##          </file>

Also there is an issue with the update. I dont know exactly what is the issue. If you could tell me it'll be great. When I take the db table dumps of snowbabel from my old snowbabel version. The user defined translations come in Backend. But if I run the scheduler every translations other than the default local lang files from the extension folder will gone. 

Please revert ASAP!!!!

Thanks in advance.....

**Comment by ghost** [comment]
Hi ! 
I've got the same problem with a lang file without a body tag.
What can be done ?

**Comment by shyam-k** [comment]
Hi

i have fix the issue by adding function to handle old formatted xml language files and you can found it on below . could you please review the code and add it to snowbabel extension with next release.

Updated code of Translations.php file

replace function updateTranslation with following code on line 292 of Translations.php file

``` php
    public function updateTranslation($Translation) {

        $FilePath = $Translation['ExtensionPath'] . $Translation['FileKey'];
        $LanguageKey = $Translation['TranslationLanguage'];
        $ExtensionKey = $Translation['ExtensionKey'];
        $LabelName = $Translation['LabelName'];
        $TranslationValue = $Translation['TranslationValue'];

        // Get l10n Location
        $TranslationFileName = GeneralUtility::llXmlAutoFileName($FilePath, $LanguageKey);
        $TranslationFilePath = GeneralUtility::getFileAbsFileName($TranslationFileName);

        // Update XLIFF
        //self::updateTranslationXlf($TranslationValue, $LabelName, $LanguageKey, $TranslationFilePath, $ExtensionKey);

        // Delete Temp Files In typo3temp-Folder
        //self::deleteSystemCache($FilePath, $LanguageKey);

        /*
        * Custom code for handling the old xml file language files 
        #################################################################
        */
        $info = pathinfo($TranslationFilePath);
        $extension = $info['extension'];
        if($extension == 'xml'){
            //\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($info);
            self::updateTranslationXml($TranslationValue, $LabelName, $LanguageKey, $TranslationFilePath, $ExtensionKey);
            self::deleteSystemCache($FilePath, $LanguageKey);

        }else
        {
            // Update XLIFF
            self::updateTranslationXlf($TranslationValue, $LabelName, $LanguageKey, $TranslationFilePath, $ExtensionKey);

            // Delete Temp Files In typo3temp-Folder
            self::deleteSystemCache($FilePath, $LanguageKey);
        }

        /*##############################################################*/
    }

```

and add new following function function to  Translations.php file

``` php
    /**
     * @param $TranslationValue
     * @param $LabelName
     * @param $LanguageKey
     * @param $TranslationFilePath
     * @param $ExtensionKey
     * @return void
     */
    private function updateTranslationXml($TranslationValue, $LabelName, $LanguageKey, $TranslationFilePath, $ExtensionKey){

        $Translation = self::getSystemLanguageFileXml($TranslationFilePath);
        if(strlen($TranslationValue)) {
            $Translation['data'][$LanguageKey][$LabelName] = $TranslationValue;
        }else{
            if($Translation['data'][$LanguageKey][$LabelName]) {
                unset($Translation['data'][$LanguageKey][$LabelName]);
            }
            echo $Translation['data'][$LanguageKey][$LabelName];
        }
        $SaveToOriginal = 0;  
        $XmlOptions = array(
            'parentTagMap' => array(
                'data' => 'languageKey',
                'orig_hash' => 'languageKey',
                'orig_text' => 'languageKey',
                'labelContext' => 'label',
                'languageKey' => 'label'
            )
        );


        $XmlFile = '<?xml version="1.0" encoding="utf-8" standalone="yes" ?>' . chr(10);
        $XmlFile .= GeneralUtility::array2xml($Translation, '', 0, $SaveToOriginal ? 'T3locallang' : 'T3locallangExt', 0, $XmlOptions);
        GeneralUtility::writeFile($TranslationFilePath, $XmlFile);
    }

```
