### ISSUE TITLE
Issue after Updated Snowbabel  

### ISSUE THREAD

**Issue by hojaonline** [snowflakech/snowbabel#7]
I've updated snowbabel extension. After update the scheduler not runs perfectly. It throws error. ["The execution failed, but the error message could not be retrieved (it was probably too large). Sorry."]. Can you please help to sort it out.

**Comment by dalder** [comment]
Hi, are you trying to index a known extension (which one)?
Otherwise it is a little bit hard to find out what the issue could be... maybe I am able to reproduce the problem.

Thanks for providing some insight informations!

**Comment by hojaonline** [comment]
Hi, Daniel

Thanks for the reply. Actually now there is only one of my custom extension is listing in the snowbabel backend after upgrade. When I run scheduler it is showing this error.

**Comment by hojaonline** [comment]
I've a lot of known extensions like powermail also. They are also not listing.

**Comment by dalder** [comment]
Did you try to add/remove all of your extension one after another via the settings module?
Then run the indexing task. Continue as long as the error shows up. This could lead you to the problematic extension. If you found the extension which leads to break the indexing task, tell me. If the extension is available I could try by my self to find the error.

I do need some detail information, about the error, where it breaks, any output?
Otherwise is near impossible to help you...

**Comment by hojaonline** [comment]
Hi Daniel,
I've found the issue is due to extensions with no locallang files is added for index extension settings. If I remove those extensions from the index queue the scheduler and it works good now. Can you please implement a check for file inside the extension path and revert no action for no locallang found case.
